name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Landing page
      id: landing-page
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Landing page
        setup-command: npm install; npx --yes json-server & db.json & npm run dev
        command: " npx -y cypress run --spec cypress/e2e/landing-page.cy.js --env
          SERVER_PORT=5173"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LANDING-PAGE_RESULTS: "${{steps.landing-page.outputs.result}}"
      with:
        runners: landing-page
